

const enterpriseThemeV020 = {
  hashed: true,
  token: {
    colorPrimary: "#1f6feb",
    colorInfo: "#1f6feb",
    colorSuccess: "#059669",
    colorWarning: "#d97706",
    colorError: "#e11d48",
    colorText: "#1f2024",
    colorTextSecondary: "#4f5560",
    colorTextTertiary: "#6b7280",
    colorTextQuaternary: "#9ca3af",
    colorBgLayout: "#f5f7fa",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBorder: "#d3d5da",
    colorBorderSecondary: "#e5e7eb",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    fontSize: 14,
    borderRadius: 6,
    borderRadiusLG: 8,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 40,
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    motionDurationFast: "0.15s",
    motionDurationMid: "0.2s",
    motionDurationSlow: "0.3s",
    boxShadow: "0 2px 8px rgba(31, 32, 36, 0.08)",
    boxShadowSecondary: "0 6px 20px rgba(31, 32, 36, 0.12)",
  },
  components: {
    Layout: {
      bodyBg: "#f5f7fa",
      headerBg: "#ffffff",
      siderBg: "#ffffff",
      headerHeight: 48,
      headerPadding: "0 16px",
    },
    Menu: {
      itemHeight: 36,
      itemBg: "#ffffff",
      itemColor: "#4f5560",
      itemHoverBg: "#eff6ff",
      itemHoverColor: "#1d4ed8",
      itemSelectedBg: "#e8f1ff",
      itemSelectedColor: "#1d4ed8",
      subMenuItemBg: "#ffffff",
    },
    Button: {
      controlHeight: 36,
      controlHeightSM: 28,
      fontSize: 14,
      fontSizeSM: 12,
      borderRadius: 6,
      defaultBg: "#ffffff",
      defaultBorderColor: "#d3d5da",
      defaultColor: "#4f5560",
      primaryShadow: "0 1px 2px rgba(31, 111, 235, 0.16)",
      dangerShadow: "0 1px 2px rgba(225, 29, 72, 0.14)",
    },
    Input: {
      controlHeight: 36,
      fontSize: 12,
      colorBgContainer: "#ffffff",
      activeBorderColor: "#9ca3af",
      hoverBorderColor: "#9ca3af",
      activeShadow: "0 0 0 2px rgba(31, 111, 235, 0.10)",
      errorActiveShadow: "0 0 0 2px rgba(225, 29, 72, 0.10)",
    },
    Select: {
      controlHeight: 36,
      fontSize: 14,
      activeBorderColor: "#9ca3af",
      hoverBorderColor: "#9ca3af",
      activeOutlineColor: "rgba(31, 111, 235, 0.10)",
      optionActiveBg: "#eff6ff",
      optionSelectedBg: "#e8f1ff",
      optionSelectedColor: "#1d4ed8",
    },
    Table: {
      fontSize: 12,
      headerBg: "#ffffff",
      headerColor: "#6b7280",
      headerBorderRadius: 0,
      borderColor: "#e5e7eb",
      rowHoverBg: "#f7faff",
      rowSelectedBg: "#f3f7ff",
      rowSelectedHoverBg: "#edf4ff",
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 12,
    },
    Form: {
      labelColor: "#4f5560",
      labelFontSize: 12,
      verticalLabelPadding: "0 0 4px",
      itemMarginBottom: 12,
    },
    Modal: {
      titleFontSize: 14,
      titleColor: "#1f2024",
      headerBg: "#ffffff",
      contentBg: "#ffffff",
      footerBg: "#ffffff",
    },
    Drawer: {
      colorBgElevated: "#ffffff",
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Tabs: {
      itemColor: "#4f5560",
      itemHoverColor: "#1f6feb",
      itemSelectedColor: "#1f6feb",
      itemActiveColor: "#1d4ed8",
      inkBarColor: "#1f6feb",
      titleFontSizeSM: 12,
      horizontalItemPaddingSM: "6px 12px",
      cardBg: "#f9fafb",
    },
    Pagination: {
      itemBg: "#ffffff",
      itemActiveBg: "#ffffff",
      itemSizeSM: 24,
      fontSizeSM: 12,
    },
    Tag: {
      defaultBg: "#f9fafb",
      defaultColor: "#4b5563",
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "8px 12px",
      zIndexPopup: 1010,
    },
    Upload: {
      actionsColor: "#4f5560",
    },
  },
};

const enterpriseUiStandards = Object.freeze({
  colors: Object.freeze({
    text: "#172033",
    textSecondary: "#69758b",
    textTertiary: "#94a0b4",
    border: "#e5eaf2",
    borderStrong: "#d1d9e7",
    page: "#eef2f7",
    container: "#ffffff",
    forecastPrimary: "#4865f2",
  }),
  typography: Object.freeze({
    title: 13,
    body: 12,
    help: 11,
    regular: 400,
    medium: 500,
    semibold: 600,
  }),
  spacing: Object.freeze({ xxs: 2, xs: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 24 }),
  forecastTable: Object.freeze({
    headerBackground: "#f7f9fc",
    weekHeaderBackground: "#e9eef8",
    dayHeaderBackground: "#f2f5fb",
    parentRowBackground: "#f7f9fc",
    finalRowBackground: "#ffffff",
    weekendBackground: "#fafafa",
    headerText: "#53658b",
    dayHeaderText: "#4c5a76",
    parentText: "#32405d",
    manualText: "#3f5bdc",
    toggleBorder: "#acbad0",
    toggleText: "#526078",
    resizeGuide: "#aebbe5",
    gridBorder: "#e5eaf2",
    weekBoundary: "#b4c3df",
    parentBoundary: "#ced8eb",
    crossHighlight: "rgba(31, 111, 235, .045)",
    focusBorder: "rgba(31, 111, 235, .18)",
    weekHeaderHeight: 28,
    dayHeaderHeight: 34,
    systemRowHeight: 40,
    editableRowHeight: 54,
    finalRowHeight: 55,
    dayWidth: 72,
    weekTotalWidth: 112,
    keyboardResizeStep: 8,
  }),
  tableAlignment: Object.freeze({
    text: "left",
    number: "right",
    selection: "center",
    forecastMatrix: "left",
  }),
  icons: Object.freeze({
    search: "SearchOutlined",
    settings: "SettingOutlined",
    more: "MoreOutlined",
    edit: "EditOutlined",
    delete: "DeleteOutlined",
    add: "PlusOutlined",
    refresh: "ReloadOutlined",
    warning: "WarningOutlined",
    pin: "PushpinOutlined",
    top: "VerticalAlignTopOutlined",
    move: "HolderOutlined",
    lock: "LockOutlined",
    store: "ShopOutlined",
  }),
});

window.EnterpriseUiStandards = enterpriseUiStandards;
