

const enterpriseThemeV020 = {
  hashed: true,
  token: {
    colorPrimary: "#1f6feb",
    colorInfo: "#1f6feb",
    colorSuccess: "#059669",
    colorWarning: "#d97706",
    colorError: "#e11d48",
    colorText: "#1f2024",
    colorTextSecondary: "#4f5560",
    colorTextTertiary: "#6b7280",
    colorTextQuaternary: "#9ca3af",
    colorBgLayout: "#f5f7fa",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBorder: "#d3d5da",
    colorBorderSecondary: "#e5e7eb",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    fontSize: 14,
    borderRadius: 6,
    borderRadiusLG: 8,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 40,
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    motionDurationFast: "0.15s",
    motionDurationMid: "0.2s",
    motionDurationSlow: "0.3s",
    boxShadow: "0 2px 8px rgba(31, 32, 36, 0.08)",
    boxShadowSecondary: "0 6px 20px rgba(31, 32, 36, 0.12)",
  },
  components: {
    Layout: {
      bodyBg: "#f5f7fa",
      headerBg: "#ffffff",
      siderBg: "#ffffff",
      headerHeight: 48,
      headerPadding: "0 16px",
    },
    Menu: {
      itemHeight: 36,
      itemBg: "#ffffff",
      itemColor: "#4f5560",
      itemHoverBg: "#eff6ff",
      itemHoverColor: "#1d4ed8",
      itemSelectedBg: "#e8f1ff",
      itemSelectedColor: "#1d4ed8",
      subMenuItemBg: "#ffffff",
    },
    Button: {
      controlHeight: 36,
      controlHeightSM: 28,
      fontSize: 14,
      fontSizeSM: 12,
      borderRadius: 6,
      defaultBg: "#ffffff",
      defaultBorderColor: "#d3d5da",
      defaultColor: "#4f5560",
      primaryShadow: "0 1px 2px rgba(31, 111, 235, 0.16)",
      dangerShadow: "0 1px 2px rgba(225, 29, 72, 0.14)",
    },
    Input: {
      controlHeight: 36,
      fontSize: 12,
      colorBgContainer: "#ffffff",
      activeBorderColor: "#9ca3af",
      hoverBorderColor: "#9ca3af",
      activeShadow: "0 0 0 2px rgba(31, 111, 235, 0.10)",
      errorActiveShadow: "0 0 0 2px rgba(225, 29, 72, 0.10)",
    },
    Select: {
      controlHeight: 36,
      fontSize: 14,
      activeBorderColor: "#9ca3af",
      hoverBorderColor: "#9ca3af",
      activeOutlineColor: "rgba(31, 111, 235, 0.10)",
      optionActiveBg: "#eff6ff",
      optionSelectedBg: "#e8f1ff",
      optionSelectedColor: "#1d4ed8",
    },
    Table: {
      fontSize: 12,
      headerBg: "#ffffff",
      headerColor: "#6b7280",
      headerBorderRadius: 0,
      borderColor: "#e5e7eb",
      rowHoverBg: "#f7faff",
      rowSelectedBg: "#f3f7ff",
      rowSelectedHoverBg: "#edf4ff",
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 12,
    },
    Form: {
      labelColor: "#4f5560",
      labelFontSize: 12,
      verticalLabelPadding: "0 0 4px",
      itemMarginBottom: 12,
    },
    Modal: {
      titleFontSize: 14,
      titleColor: "#1f2024",
      headerBg: "#ffffff",
      contentBg: "#ffffff",
      footerBg: "#ffffff",
    },
    Drawer: {
      colorBgElevated: "#ffffff",
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
      zIndexPopup: 1000,
    },
    Tabs: {
      itemColor: "#4f5560",
      itemHoverColor: "#1f6feb",
      itemSelectedColor: "#1f6feb",
      itemActiveColor: "#1d4ed8",
      inkBarColor: "#1f6feb",
      titleFontSizeSM: 12,
      horizontalItemPaddingSM: "6px 12px",
      cardBg: "#f9fafb",
    },
    Pagination: {
      itemBg: "#ffffff",
      itemActiveBg: "#ffffff",
      itemSizeSM: 24,
      fontSizeSM: 12,
    },
    Tag: {
      defaultBg: "#f9fafb",
      defaultColor: "#4b5563",
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "8px 12px",
      zIndexPopup: 1010,
    },
    Upload: {
      actionsColor: "#4f5560",
    },
  },
};
