const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']}),page=await ctx.newPage(),errors=[];
 page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const id='US-B0GRG5DRWW',goods=page.locator('[data-record-id="'+id+'"]'),toggle=()=>page.locator('[data-forecast-toggle-button="all"]'),history=()=>page.locator('[data-history-entry="'+id+'"]'),count=()=>page.locator('[data-history-count="'+id+'"]'),rows=()=>page.locator('[data-child-row="'+id+'"]'),historyRows=()=>page.locator('[data-history-for="'+id+'"]');
 const dialog=name=>page.getByRole('dialog',{name,exact:true}),shot=n=>page.screenshot({path:path.join(__dirname,'evidence','v027-'+n+'.png'),animations:'disabled'}),save=async name=>{await dialog(name).getByRole('button',{name:'保存',exact:true}).click();await dialog(name).waitFor({state:'hidden'});};
 const final=i=>page.locator('[data-final="'+id+'"][data-index="'+i+'"]'),manual=i=>page.locator('[data-edit-manual="'+id+'"][data-index="'+i+'"]');
 const quantity=async(i,n,reason)=>{await manual(i).click();await page.getByRole('spinbutton',{name:'预测销量'}).fill(String(n));await page.getByRole('textbox',{name:'人工预测原因'}).fill(reason);await save('人工预测');};
 const manage=async name=>{await count().click();await page.getByRole('menuitem',{name,exact:true}).click();};
 try{
  await page.goto('http://127.0.0.1:8800/?v=0.2.7');await toggle().waitFor();assert.deepEqual(errors,[]);
  assert.equal(await rows().count(),4);assert.equal(await toggle().textContent(),'');assert.equal(await page.locator('[data-forecast-line="controls"],.history-load-row,[data-history-loader]').count(),0);
  const index=await page.evaluate(()=>indexForDate('2026-10-21'));assert.equal(await manual(index).locator('.entry-number').textContent(),'');assert.equal(await page.locator('[data-event="'+id+'"][data-date="2026-10-21"] .entry-number').textContent(),'');
  assert.equal(await page.locator('.source-tag').first().evaluate(e=>getComputedStyle(e).fontSize),'11px');assert.equal(await page.locator('.current-week-label').count(),1);assert.match(await page.locator('.current-forecast-week').textContent(),/W43/);
  const details=await goods.innerText();assert.match(details,/A1B2C3D\s+N0C0001A-91-XL/);assert.equal(await goods.locator('.biz-code').evaluate(e=>getComputedStyle(e,'::before').content),'"丨"');assert.match(details,/上架/);assert.equal(await goods.locator('.product-actions button').count(),3);await shot('default');
  await history().click();assert.equal(await historyRows().count(),4);assert.match(await count().textContent(),/2\/6/);assert.ok((await historyRows().locator('[data-history-kind="actual"]').allTextContents()).every(t=>t===''));
  await toggle().click();assert.equal(await rows().count(),1);assert.equal(await historyRows().count(),4);assert.ok((await goods.innerText()).includes('A1B2C3D'));assert.ok(await goods.locator('.product-note').isVisible());await shot('collapsed');
  await history().click();assert.equal(await historyRows().count(),0);assert.equal(await rows().count(),1);await history().click();await toggle().click();assert.equal(await rows().count(),4);
  await manage('再加载2批（剩余4批）');assert.equal(await historyRows().count(),6);await manage('展开全部6批');assert.equal(await historyRows().count(),8);await manage('仅保留最近2批');assert.equal(await historyRows().count(),4);
  await page.locator('[data-history-part="'+id+'|2026-10-14"]').click();assert.equal(await historyRows().count(),7);assert.equal(await page.locator('.history-component').count(),3);await shot('history-components');await page.locator('[data-history-part="'+id+'|2026-10-14"]').click();
  assert.equal(await historyRows().locator('.delta').first().evaluate(e=>getComputedStyle(e).fontSize),'11px');await count().click();await page.getByRole('menuitem',{name:'再加载2批（剩余4批）',exact:true}).hover();await shot('history-menu');await page.keyboard.press('Escape');
  console.log('PASS independent forecast/history controls, inline history management, preserved details, empty defaults');

  await quantity(index,0,'暂停推广，预计无销量');assert.equal((await final(index).textContent()).replace(/\s/g,''),'0(人工)');
  await page.locator('[data-event="'+id+'"][data-date="2026-10-21"]').click();await page.getByRole('spinbutton',{name:'预测销量'}).fill('0');await page.getByRole('textbox',{name:'活动名称'}).fill('活动暂停');await page.getByRole('textbox',{name:'备注说明'}).fill('当日活动暂停');await save('活动预测');assert.equal((await final(index).textContent()).replace(/\s/g,''),'0(活动)');assert.match(await final(index+1).textContent(),/\(AI\)/);
  await page.locator('[data-event="'+id+'"][data-date="2026-10-21"]').click();await dialog('活动预测').getByRole('button',{name:'清除预测',exact:true}).click();await dialog('活动预测').waitFor({state:'hidden'});assert.equal((await final(index).textContent()).replace(/\s/g,''),'0(人工)');
  await manual(index).click();await dialog('人工预测').getByRole('button',{name:'清除预测',exact:true}).click();await dialog('人工预测').waitFor({state:'hidden'});assert.equal((await final(index).textContent()).replace(/\s/g,''),'32(AI)');
  await manual(index).click();await page.getByRole('spinbutton',{name:'预测销量'}).fill('1234');await dialog('人工预测').getByRole('button',{name:'保存',exact:true}).click();await page.getByText('请填写不采用AI预测的原因',{exact:true}).waitFor();
  const reason='新增资源投放，结合近期转化调整。'.repeat(12);await page.getByRole('textbox',{name:'人工预测原因'}).fill('字'.repeat(201));assert.equal((await page.getByRole('textbox',{name:'人工预测原因'}).inputValue()).length,200);
  const counter=await dialog('人工预测').getByText('200 / 200',{exact:true}).boundingBox(),input=await page.getByRole('textbox',{name:'人工预测原因'}).boundingBox();assert.ok(counter.x>=input.x&&counter.y+counter.height<=input.y+input.height);await page.getByRole('textbox',{name:'人工预测原因'}).fill(reason);await page.getByText('请填写不采用AI预测的原因',{exact:true}).waitFor({state:'hidden'});await dialog('人工预测').getByRole('button',{name:'保存',exact:true}).hover();await shot('manual-editor');await save('人工预测');assert.equal((await final(index).textContent()).replace(/\s/g,''),'1,234(人工)');
  const snippet=page.locator('[data-reason-host="'+id+'"][data-reason-kind="manual"]').first().locator('.cell-reason');assert.ok(await snippet.evaluate(e=>e.scrollHeight>e.clientHeight));await snippet.focus();await page.getByRole('tooltip').filter({hasText:'新增资源投放'}).waitFor();await page.locator('.range-meta').click();
  await page.locator('[data-note-edit="'+id+'"]').click();await page.getByRole('textbox',{name:'商品备注',exact:true}).fill('复核活动资源');await page.locator('.inline-note-editor').getByRole('button',{name:'保存',exact:true}).click();await page.reload();await toggle().waitFor();assert.equal(await snippet.textContent(),reason);assert.match(await goods.innerText(),/复核活动资源/);
  await manual(index).hover();const cross=await page.evaluate(()=>{const a=document.querySelector('.focus-cross-cell'),b=document.querySelector('[data-forecast-line="final"] .focus-cross-column');return [getComputedStyle(a).getPropertyValue('--cross-row').trim(),getComputedStyle(a).getPropertyValue('--cross-column').trim(),getComputedStyle(a).backgroundImage,getComputedStyle(b).getPropertyValue('--cross-column').trim(),getComputedStyle(b).backgroundImage,getComputedStyle(a).cursor];});assert.equal(cross[0],cross[1]);assert.match(cross[2],/linear-gradient.*linear-gradient/);assert.equal(cross[3],cross[1]);assert.match(cross[4],/linear-gradient.*linear-gradient/);assert.notEqual(cross[5],'crosshair');await shot('crosshair');
  await page.mouse.move(10,10);assert.equal(await manual(index).locator('.edit-icon').evaluate(e=>getComputedStyle(e).opacity),'0');
  console.log('PASS blank vs zero, activity/manual/AI fallback, reason validation/counter/truncation, persistence and crosshair layers');

  const expected={'过去7天':['2026-10-14','2026-10-20',7],'过去14天':['2026-10-07','2026-10-20',14],'过去30天':['2026-09-21','2026-10-20',30],'过去60天':['2026-08-22','2026-10-20',60],'过去90天':['2026-07-23','2026-10-20',90],'本月':['2026-10-01','2026-10-20',20],'上月':['2026-09-01','2026-09-30',30],'今年':['2026-01-01','2026-10-20',293],'去年':['2025-01-01','2025-12-31',365]};
  for(const [name,[a,b,n]] of Object.entries(expected)){await page.locator('#browse-range-start').click();await page.getByText(name,{exact:true}).click();await page.waitForFunction(a=>dateKey(visibleDays()[0])===a,a);const ds=await page.evaluate(()=>visibleDays().map(dateKey));assert.deepEqual([ds[0],ds.at(-1),ds.length],[a,b,n]);assert.equal(await page.locator('[data-edit-manual],[data-event]').count(),0);assert.ok((await rows().locator('.date-col').allTextContents()).every(t=>t.trim()===''));if(n>31)assert.ok(await page.locator('.date-head').count()<60);}
  await shot('past-year');assert.equal(await page.locator('.current-week-label').count(),0);await page.locator('[data-week-toggle]').first().click();assert.ok(await page.locator('.date-head:not(.week-summary)').count()>0);
  await page.locator('#browse-range-start').click();await page.getByText('过去7天',{exact:true}).click();assert.equal(await historyRows().locator('[data-history-kind="final"] .history-value').first().textContent(),'34');assert.ok(Number(await historyRows().locator('[data-history-kind="actual"] .history-value').first().textContent())>0);await shot('past-seven');
  await page.locator('#browse-range-start').click();await page.locator('td[title="2026-10-21"]').last().click();await page.locator('td[title="2026-10-27"]').last().click();await page.waitForFunction(()=>dateKey(visibleDays()[0])==='2026-10-21');await page.locator('[data-range-size="14"]').click();assert.equal(await manual(index).locator('.entry-number').textContent(),'1,234');
  console.log('PASS nine T+1 presets, historical read-only/blank current values, aligned actuals and return to current input');

  const widths=()=>page.locator('th.identity-head,th.size-head,th.context-head,th.line-head,th.date-head').evaluateAll(es=>es.map(e=>Math.round(e.getBoundingClientRect().width)));
  const ws=await widths();assert.deepEqual(ws.slice(0,4),[330,52,158,108]);await page.locator('[data-range-size="30"]').click();assert.deepEqual((await widths()).slice(0,5),ws.slice(0,5));await page.locator('[data-range-size="14"]').click();
  const alignment=await page.evaluate(()=>{const x=e=>{const tree=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);let n;while(n=tree.nextNode())if(n.textContent.trim()){const r=document.createRange();r.selectNode(n);return r.getBoundingClientRect().x;}};return ['th.date-head[data-focus-index="0"]','.current-forecast-week .week-heading > span','[data-child-row="US-B0GRG5DRWW"][data-forecast-line="system"] [data-focus-index="0"]','[data-child-row="US-B0GRG5DRWW"][data-forecast-line="manual"] [data-focus-index="0"]','[data-child-row="US-B0GRG5DRWW"][data-forecast-line="final"] [data-focus-index="0"]'].map(s=>x(document.querySelector(s)));});assert.ok(Math.max(...alignment)-Math.min(...alignment)<1.1,alignment);
  await page.locator('.current-forecast-week [data-week-toggle]').click();const weekBox=await page.locator('.current-forecast-week').boundingBox(),badge=await page.locator('.current-week-label').boundingBox();assert.ok(badge.x+badge.width<=weekBox.x+weekBox.width);assert.equal(weekBox.width,144);assert.ok((await rows().filter({has:page.locator('.line-manual')}).locator('.date-col').allTextContents()).slice(1).every(t=>t.trim()===''));await shot('current-week-collapsed');await page.locator('.current-forecast-week [data-week-toggle]').click();
  const hb=await page.locator('[data-resize-column="identity"]').boundingBox();await page.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await page.mouse.down();await page.mouse.move(hb.x+hb.width/2-24,hb.y+hb.height/2,{steps:8});await page.mouse.up();const resized=(await widths())[0];assert.equal(resized,306);await page.reload();await toggle().waitFor();assert.equal((await widths())[0],resized);
  const thumb=page.locator('.horizontal-scroll-thumb'),tb=await thumb.boundingBox();await page.mouse.move(tb.x+tb.width/2,tb.y+1);await page.mouse.down();const positions=[];for(let n=1;n<=5;n++){await page.mouse.move(tb.x+tb.width/2+n*25,tb.y+1);positions.push(await page.locator('#workbench').evaluate(e=>e.scrollLeft));}await page.mouse.up();assert.ok(positions.every((x,i)=>!i||x>positions[i-1]));await page.locator('#horizontalScrollbar').focus();await page.keyboard.press('Home');
  const headY=await page.locator('.date-head').first().evaluate(e=>e.getBoundingClientRect().top);await page.locator('#workbench').evaluate(e=>e.scrollTop=400);assert.equal(await page.locator('.date-head').first().evaluate(e=>e.getBoundingClientRect().top),headY);await page.locator('#workbench').evaluate(e=>e.scrollTop=0);
  for(const [width,height]of [[1366,768],[1440,900],[1920,900]]){await page.setViewportSize({width,height});assert.equal(await page.locator('.list-footer').evaluate(e=>e.getBoundingClientRect().bottom),height);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const bar=await page.locator('.horizontal-scrollbar').boundingBox(),foot=await page.locator('.list-footer').boundingBox();assert.ok(bar.y+bar.height<=foot.y+1);await page.mouse.move(10,10);await shot('layout-'+width);}
  await page.setViewportSize({width:1440,height:900});await page.getByRole('button',{name:'列配置',exact:true}).click();assert.equal(await page.locator('[data-antd-config-field="identity"]').isDisabled(),true);const stock=page.locator('[data-selected-field="stock"]');await stock.scrollIntoViewIfNeeded();await stock.hover();await stock.getByRole('button',{name:'置顶可售库存',exact:true}).click();await shot('columns');await dialog('列配置').getByRole('button',{name:'保存并应用',exact:true}).click();await dialog('列配置').waitFor({state:'hidden'});assert.equal(await rows().first().locator('.metric').first().getAttribute('data-field'),'stock');
  await page.getByRole('button',{name:'列配置',exact:true}).click();await dialog('列配置').getByRole('button',{name:'恢复默认',exact:true}).click();await dialog('列配置').getByRole('button',{name:'保存并应用',exact:true}).click();await dialog('列配置').waitFor({state:'hidden'});
  const skc=page.locator('.parent-skc').first();await skc.hover();await skc.locator('.copy-code').click();await page.getByText('已复制',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'C0001A-91');const message=await page.getByText('已复制',{exact:true}).boundingBox(),wb=await page.locator('#workbench').boundingBox();assert.ok(message.y<wb.y+10);assert.ok(Math.abs(message.x+message.width/2-wb.x-wb.width/2)<25);
  console.log('PASS fixed/persisted column widths, draggable scrollbar, sticky header/footer, three viewports, configured metric order and code copying');

  const drawer=dialog('商品详情');for(const view of ['sales','analysis','mapping']){await page.locator('[data-insight="'+view+'"][data-asin="'+id+'"]').click();await drawer.waitFor();assert.equal(await drawer.getByRole('tab').count(),3);assert.equal(await page.locator('[data-insight-panel]').getAttribute('data-insight-panel'),view);if(view==='sales'){await page.waitForFunction(()=>Boolean(echarts.getInstanceByDom(document.querySelector('.sales-echart'))?.getOption()?.series?.length));assert.equal(await drawer.getByRole('checkbox',{name:'对比上期',exact:true}).count(),1);await shot('sales-drawer');}await drawer.getByRole('tab',{name:'SKU映射',exact:true}).click();assert.equal(await drawer.getByRole('tab').count(),3);const code=drawer.locator('.insight-identity .insight-copy-code');await page.mouse.move(10,10);assert.equal(await code.locator('.insight-copy-action').evaluate(e=>getComputedStyle(e).opacity),'0');await code.hover();assert.equal(await code.locator('.insight-copy-action').evaluate(e=>getComputedStyle(e).opacity),'1');await drawer.getByRole('button',{name:'Close',exact:true}).click();await drawer.waitFor({state:'hidden'});}
  assert.equal(await page.getByText('商品档案',{exact:true}).count(),0);await page.goto('http://127.0.0.1:8800/index.v0.2.6.html');await page.locator('#antdColumnButton').waitFor();assert.equal(await page.locator('script[src*="v027"],link[href*="v027"]').count(),0);assert.deepEqual(errors,[]);
  console.log('V027 PASS: compatibility baseline checked; zero page/console errors. Screenshots in evidence/v027-*.png.');
 }catch(e){console.error(e);console.error(errors);await shot('failure');process.exitCode=1;}finally{await browser.close();}
})();
