const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']}),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(12000);
 page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const id='US-B0GRG5DRWW',goods=page.locator('[data-record-id="'+id+'"]'),toggle=()=>page.locator('[data-forecast-toggle-button="all"]');
 const shot=n=>page.screenshot({path:path.join(__dirname,'evidence','v026-'+n+'.png'),animations:'disabled'});
 const range=()=>page.evaluate(()=>visibleDays().map(dateKey));
 const preset=async(name)=>{await page.locator('#browse-range-start').click();await page.getByText(name,{exact:true}).click();await page.waitForFunction(()=>!document.querySelector('td[title="2026-10-14"]')||document.querySelector('td[title="2026-10-14"]').getBoundingClientRect().height===0).catch(()=>{});};
 try{
  await page.goto('http://127.0.0.1:8800/?v=0.2.6');await toggle().waitFor();assert.deepEqual(errors,[]);
  assert.equal(await page.locator('.line-head [data-forecast-toggle-button]').count(),1);assert.equal(await page.locator('[data-forecast-line="controls"]').count(),0);assert.equal(await page.locator('[data-child-row="'+id+'"]').count(),4);
  assert.equal(await page.getByText('商品档案',{exact:true}).count(),0);assert.equal(await page.locator('.range-title > span').innerText(),'预测范围');
  const details=await goods.innerText();await toggle().click();assert.equal(await page.locator('[data-child-row="'+id+'"]').count(),1);assert.equal(await goods.innerText(),details);assert.ok(await goods.locator('.product-actions').isVisible());await shot('collapsed');await toggle().click();
  assert.equal(await page.locator('.source-tag').first().evaluate(e=>getComputedStyle(e).fontSize),'11px');
  await shot('default');await page.locator('[data-history-toggle="'+id+'"]').click();await page.locator('[data-history-loader="'+id+'"]').waitFor();
  assert.equal(await page.locator('.history-load-row').count(),0);assert.equal(await page.locator('[data-history-for="'+id+'"]').count(),4);assert.equal(await page.locator('[data-history-loader="'+id+'"]').evaluate(e=>e.closest('tr').classList.contains('history-tail')),true);await shot('history-two');
  const loaderX=(await page.locator('[data-history-loader="'+id+'"]').boundingBox()).x;await page.locator('#workbench').evaluate(e=>e.scrollLeft=350);assert.ok(Math.abs((await page.locator('[data-history-loader="'+id+'"]').boundingBox()).x-loaderX)<2);await page.locator('#workbench').evaluate(e=>e.scrollLeft=0);
  await page.getByRole('button',{name:'加载更多历史批次 B0GRG5DRWW',exact:true}).click();assert.equal(await page.locator('[data-history-for="'+id+'"]').count(),6);await shot('history-four');await page.getByRole('button',{name:'加载更多历史批次 B0GRG5DRWW',exact:true}).click();assert.equal(await page.locator('[data-history-for="'+id+'"]').count(),8);
  await page.getByRole('button',{name:'收起更多历史批次 B0GRG5DRWW',exact:true}).click();assert.equal(await page.locator('[data-history-for="'+id+'"]').count(),4);
  const expected={'过去7天':['2026-10-14','2026-10-20',7],'过去14天':['2026-10-07','2026-10-20',14],'过去30天':['2026-09-21','2026-10-20',30],'过去60天':['2026-08-22','2026-10-20',60],'过去90天':['2026-07-23','2026-10-20',90],'本月':['2026-10-01','2026-10-20',20],'上月':['2026-09-01','2026-09-30',30],'今年':['2026-01-01','2026-10-20',293],'去年':['2025-01-01','2025-12-31',365]};
  for(const [name,[a,b,n]]of Object.entries(expected)){await preset(name);const ds=await range();assert.equal(ds[0],a);assert.equal(ds.at(-1),b);assert.equal(ds.length,n);assert.equal(await page.locator('[data-edit-manual],[data-event]').count(),0);assert.equal(await page.locator('#coverageRange').textContent(),'2026/10/21 - 2027/04/20');if(n>31)assert.ok(await page.locator('.date-head').count()<60);}
  await shot('past-year');const actual=page.locator('[data-history-for="'+id+'"] [data-history-kind="actual"] .history-value').first();assert.ok(Number((await actual.innerText()).replaceAll(',',''))>0);
  const week=page.locator('[data-week-toggle]').first(),before=await page.locator('.date-head').count();await week.click();assert.equal(await page.locator('.date-head').count(),before+4);await shot('year-week-expanded');
  await preset('过去7天');assert.equal(await page.locator('[data-history-for="'+id+'"] [data-history-kind="final"] .history-value').first().innerText(),'34');await shot('past-seven');
  await page.locator('[data-insight="analysis"][data-asin="'+id+'"]').click();await page.getByText('本批次未覆盖所选日期',{exact:true}).waitFor();await page.getByRole('dialog',{name:'商品详情',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
  await page.locator('#browse-range-start').click();await page.locator('td[title="2026-10-21"]').last().click();await page.locator('td[title="2026-10-27"]').last().click();await page.waitForFunction(()=>dateKey(visibleDays()[0])==='2026-10-21');assert.equal(await page.locator('[data-edit-manual="'+id+'"]').count(),7);await page.locator('[data-range-size="14"]').click();
  const index=await page.evaluate(()=>indexForDate('2026-10-21'));await page.locator('[data-edit-manual="'+id+'"][data-index="'+index+'"]').click();await page.getByRole('spinbutton',{name:'预测销量'}).fill('1234');await page.getByRole('textbox',{name:'人工预测原因'}).fill('验证查看历史不改变当前提报');await page.getByRole('dialog',{name:'人工预测',exact:true}).getByRole('button',{name:'保存',exact:true}).click();
  assert.match(await page.locator('[data-final="'+id+'"][data-index="'+index+'"]').textContent(),/1,234/);
  for(const [width,height]of [[1366,768],[1440,900],[1920,900]]){await page.setViewportSize({width,height});assert.equal(await page.locator('.list-footer').evaluate(e=>e.getBoundingClientRect().bottom),height);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('layout-'+width);}
  const drawer=page.getByRole('dialog',{name:'商品详情',exact:true});for(const view of ['sales','analysis','mapping']){await page.locator('[data-insight="'+view+'"][data-asin="'+id+'"]').click();await drawer.waitFor();assert.equal(await drawer.getByRole('tab').count(),3);assert.equal(await page.locator('[data-insight-panel]').getAttribute('data-insight-panel'),view);await drawer.getByRole('tab',{name:'SKU映射',exact:true}).click();assert.equal(await drawer.getByRole('tab').count(),3);const code=drawer.locator('.insight-identity .insight-copy-code');await page.mouse.move(10,10);assert.equal(await code.locator('.insight-copy-action').evaluate(e=>getComputedStyle(e).opacity),'0');await code.hover();assert.equal(await code.locator('.insight-copy-action').evaluate(e=>getComputedStyle(e).opacity),'1');await code.getByRole('button').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'B0GRG5DRWW');await shot('mapping-hover');await drawer.getByRole('button',{name:'Close',exact:true}).click();await drawer.waitFor({state:'hidden'});}
  await page.goto('http://127.0.0.1:8800/index.v0.2.5.html');await page.locator('#antdColumnButton').waitFor();assert.equal(await page.locator('script[src*="v026"]').count(),0);assert.deepEqual(errors,[]);console.log('V026 PASS header toggle / no control or load rows / product preservation / nine historical presets / read-only and current edit / historical actuals / copy hover / three tabs / three layouts / previous entry');
 }catch(e){console.error(e);console.error(errors);await shot('failure');process.exitCode=1;}finally{await browser.close();}
})();
