const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']}),p=await ctx.newPage(),errors=[];
 p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const id='US-B0GRG5DRWW',parent='US-B0GRGFFVVN',goods=()=>p.locator('[data-record-id="'+id+'"]'),band=key=>p.locator('[data-parent-id="'+key+'"]'),shot=n=>p.screenshot({path:path.join(__dirname,'evidence','v029-'+n+'.png'),animations:'disabled'});
 try{
  await p.goto('http://127.0.0.1:8800/?v=0.2.9');await goods().locator('[data-tag-category="库存"]').waitFor();assert.deepEqual(errors,[]);
  const tags=await goods().locator('[data-tag-category]').evaluateAll(es=>es.map(e=>({text:e.textContent,color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor})));assert.deepEqual(tags.map(t=>t.text),['销售状态：已上架','生命周期：成熟款','库存：偏紧']);assert.equal(new Set(tags.map(t=>t.color)).size,3);assert.equal(new Set(tags.map(t=>t.bg)).size,3);
  const sections=await p.locator('[data-child-row="'+id+'"]').first().locator('.context-section').evaluateAll(es=>es.map(e=>[e.dataset.section,getComputedStyle(e).backgroundColor]));assert.deepEqual(sections.map(s=>s[0]),['sales','stock']);assert.notEqual(sections[0][1],sections[1][1]);
  assert.equal(await goods().locator('.store-icon svg').count(),1);assert.equal(await goods().locator('.store-name').textContent(),'BRABIC-US');assert.equal(await p.locator('.summary-row').count(),0);assert.equal(await p.getByText('Parent 合计',{exact:false}).count(),0);
  assert.equal(await band(parent).locator('.parent-child-count').textContent(),'(1)');assert.equal(await band('US-B0CP75XCTP').locator('.parent-child-count').textContent(),'(7)');assert.equal(await band('US-B0CP75XCTP').locator('.date-col').first().textContent(),'204');
  assert.equal(await p.locator('#coverageRange').textContent(),'2026/10/21 ~ 2027/04/20');assert.match(await p.locator('.forecast-range-picker-host').textContent(),/~/);assert.match(await p.locator('.current-forecast-week').textContent(),/10\/21 ~ 10\/25/);await shot('default');
  await p.locator('.current-forecast-week [data-week-toggle]').click();assert.equal(await p.locator('th.date-head.week-collapsed').first().textContent(),'10/21 ~ 10/25');await shot('week-collapsed');await p.locator('.current-forecast-week [data-week-toggle]').click();
  const parentCode=band(parent).locator('.code-value').first();await parentCode.hover();await parentCode.getByRole('button').click();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'B0GRGFFVVN');
  await p.locator('[data-collapse="'+parent+'"]').click();assert.equal(await goods().count(),0);assert.equal(await band(parent).locator('.parent-child-count').textContent(),'(1)');assert.equal(await band(parent).locator('.date-col').first().textContent(),'32');await p.locator('[data-collapse="'+parent+'"]').click();
  const index=await p.evaluate(()=>indexForDate('2026-10-21'));assert.equal(await p.locator('[data-edit-manual="'+id+'"]').first().locator('.entry-number').textContent(),'');await p.locator('[data-edit-manual="'+id+'"][data-index="'+index+'"]').click();await p.getByRole('spinbutton',{name:'预测销量'}).fill('0');await p.getByRole('textbox',{name:'人工预测原因'}).fill('暂停推广');await p.getByRole('dialog',{name:'人工预测',exact:true}).getByRole('button',{name:'保存',exact:true}).click();await p.getByRole('dialog',{name:'人工预测',exact:true}).waitFor({state:'hidden'});assert.equal(await band(parent).locator('.date-col').first().textContent(),'0');assert.equal((await p.locator('[data-final="'+id+'"]').first().textContent()).replace(/\s/g,''),'0(人工)');
  await p.locator('[data-history-entry="'+id+'"]').click();await p.locator('[data-history-for="'+id+'"]').first().waitFor();assert.equal(await p.locator('.summary-row').count(),0);await shot('history');
  await p.locator('.forecast-pagination').getByTitle('20 条/页',{exact:true}).click();await p.getByTitle('5 条/页',{exact:true}).click();await p.waitForFunction(()=>state.pageSize===5);await p.locator('.forecast-pagination').getByTitle('2',{exact:true}).click();await p.waitForFunction(()=>state.page===2);assert.equal(await band('US-B0CP75XCTP').locator('.parent-child-count').textContent(),'(5)');assert.equal(await band('US-B0CP75XCTP').locator('.date-col').first().textContent(),'149');await shot('paged-parent-count');
  await p.locator('.forecast-pagination').getByTitle('1',{exact:true}).click();await p.locator('#browse-range-start').click();await p.getByText('过去7天',{exact:true}).click();assert.equal(await p.locator('[data-edit-manual],[data-event]').count(),0);assert.equal(await band(parent).locator('.date-col').first().textContent(),'');assert.match(await p.locator('.forecast-range-picker-host').textContent(),/~/);await shot('past-seven');
  for(const [width,height]of [[1366,768],[1440,900],[1920,900]]){await p.setViewportSize({width,height});assert.equal(await p.locator('.list-footer').evaluate(e=>e.getBoundingClientRect().bottom),height);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('layout-'+width);}
  await p.reload();await goods().locator('.store-icon svg').waitFor();assert.equal(await p.locator('.summary-row').count(),0);assert.equal(await band(parent).locator('.date-col').first().textContent(),'0');
  await p.goto('http://127.0.0.1:8800/index.v0.2.8.html');await p.locator('#antdColumnButton').waitFor();assert.equal(await p.locator('script[src*="v029"],link[href*="v029"]').count(),0);assert.deepEqual(errors,[]);console.log('V029 PASS semantic colors / context sections / all list range separators / parent counts and daily sums / no duplicate total row / shop icons / pagination / blank and zero / 3 layouts / archive');
 }catch(e){console.error(e);console.error(errors);await shot('failure');process.exitCode=1;}finally{await browser.close();}
})();
