const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const ctx=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']});
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);
 const id='US-B0GRG5DRWW',uk='UK-B0GRG5DRWW',shot=async name=>{await page.locator('#toast.show').waitFor({state:'hidden'});return page.screenshot({path:path.join(__dirname,'evidence','v019-'+name+'.png')});};
 const manual=(i=0)=>page.locator(`[data-edit-manual="${id}"][data-index="${i}"]`);
 const final=(i=0)=>page.locator(`[data-final="${id}"][data-index="${i}"]`);
 const edit=async(i,v)=>{await manual(i).click();await page.locator('[data-manual]').fill(v);await page.locator('[data-manual]').press('Enter');};
 try{
  await page.goto('http://127.0.0.1:8800/?v=0.1.9');await page.locator('.site-band').first().waitFor();
  assert.deepEqual(errors,[]);assert.equal(await page.locator('[data-record-id]').count(),13);assert.equal(await page.locator('.site-band').count(),2);
  const codes=await page.evaluate(()=>groups.flatMap(g=>g.children.map(c=>({parent:g.parent,asin:c.asin,spu:g.spu,skc:g.skc,sku:c.sku,old:c.historicSku,combo:c.combo,business:c.businessCode,site:g.market}))));
  codes.forEach(c=>{assert.match(c.spu,/^[A-Z][0-9]{4}$/);assert.match(c.skc,/^[A-Z][0-9]{4}[A-Z]-\d+$/);assert.match(c.sku,/^[0-9A-Z]{7}$/);assert.match(c.old,/^[0-9A-Z]{7}$/);assert.match(c.combo,/^SC[0-9A-Z]{7}$/);assert.match(c.business,/^[A-Z][0-9]?[A-Z][0-9]{4}[A-Z]?-[0-9]+-[A-Z0-9]{1,5}$/);});
  assert.equal(codes[0].business,'N0C0001A-91-XL');assert.equal(codes[1].business,'NC0002A-92-XL');assert.equal(codes[4].business,'N0C0004-92-XL');
  assert.ok(codes.some(c=>/^\d{7}$/.test(c.sku))&&codes.some(c=>/^[A-Z]{7}$/.test(c.sku)));
  assert.deepEqual(codes.filter(c=>c.site==='US').map(c=>[c.parent,c.asin]),[
   ['B0GRGFFVVN','B0GRG5DRWW'],['B0H4QG3TLS','B0CVRKCC5M'],['B0GY4KJPF4','B0GY4LY1D7'],['B0GY4KJPF4','B0GY4PXNWR'],['B0GJT623SK','B0GJZGTZZP'],...['B0CKYMWV23','B0CKYMJ4NV','B0CKYP9WNG','B0CKYNCBDL','B0CKYMR6GJ','B0CKYL9N9X','B0CKYNWY8F'].map(c=>['B0CP75XCTP',c])]);
  await shot('default');console.log('Mock code constraints, conditional segments, exact ASIN pairs and site grouping PASS');
  await page.locator(`[data-record-id="${id}"] .biz-code`).hover();await page.locator('#codeTooltip:not([hidden])').waitFor();assert.equal(await page.locator('[role="tooltip"]:visible').count(),1);assert.match(await page.locator('#codeTooltip').textContent(),/品牌货盘 N.*独立渠道货盘 0.*尺码 XL/);
  await page.locator(`[data-record-id="${id}"] [data-copy="A1B2C3D"]`).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'A1B2C3D');
  await page.locator('[data-tree="collapse"]').click();assert.equal(await page.locator('[data-record-id]').count(),0);assert.equal(await page.locator('[data-parent-id]').count(),6);
  await page.locator('[data-tree="expand"]').click();assert.equal(await page.locator(`[data-edit-manual="${id}"]`).count(),14);assert.equal(await manual().textContent(),'');
  const frozen=await page.evaluate(()=>JSON.stringify(historicalSnapshots));
  await edit(0,'35');await edit(1,'0');assert.match(await final(0).innerText(),/35\s*人工/);assert.match(await final(1).innerText(),/0\s*人工/);
  assert.equal(await page.evaluate(()=>findChild('UK-B0GRG5DRWW').manual['2026-10-21']??null),null);
  await page.locator(`[data-event="${id}"][data-date="2026-10-21"]`).click();await page.locator('#eventQty').fill('80');await page.locator('#eventName').fill('资源加投');await page.locator('#eventNote').fill('站内大促');await page.locator('[data-action="modal-confirm"]').click();assert.match(await final().innerText(),/80\s*活动/);
  await page.locator(`[data-event="${id}"][data-date="2026-10-21"]`).click();await page.locator('#eventQty').fill('0');await page.locator('[data-action="modal-confirm"]').click();assert.match(await final().innerText(),/0\s*活动/);
  await page.locator(`[data-event="${id}"][data-date="2026-10-21"]`).click();await page.locator('[data-delete-event]').click();assert.match(await final().innerText(),/35\s*人工/);
  await edit(0,'');assert.match(await final().innerText(),/32\s*AI/);
  await page.locator(`[data-parent-check="US-B0GRGFFVVN"]`).check();assert.equal(await page.locator(`[data-row-check="${id}"]`).isChecked(),true);assert.equal(await page.locator(`[data-row-check="${uk}"]`).isChecked(),false);
  assert.equal(await page.evaluate(()=>JSON.stringify(historicalSnapshots)),frozen);console.log('Manual/event overwrite priority including zero, deletion fallback, cross-site isolation and immutable history PASS');
  await page.locator(`[data-history-toggle="${id}"]`).click();
  assert.equal(await page.locator('.history-row').count(),2);assert.equal(await page.locator('.drawer.show,.modal.show').count(),0);
  assert.ok((await page.locator('.actual-row .date-col').allTextContents()).every(t=>t==='—'));
  const historyCell=()=>page.locator('[data-history-batch="2026-10-14"][data-history-kind="final"][data-time-column="date:2026-10-21"]');
  assert.equal(await historyCell().locator('span').first().textContent(),String(await page.evaluate(()=>historicalSnapshots['2026-10-14']['US-B0GRG5DRWW']['2026-10-21'].final)));
  await page.locator(`[data-reason="${id}"]`).fill('主推资源增加');await page.locator(`[data-reason="${id}"]`).press('Tab');
  await edit(0,'40');assert.match(await historyCell().innerText(),/本次差值 \+10/);
  await page.locator(`[data-history-part="${id}|2026-10-14"]`).click();assert.equal(await page.locator('.history-component').count(),3);
  await page.locator(`[data-more-history="${id}"]`).click();assert.equal(await page.locator('.history-row').count(),4);await page.locator(`[data-less-history="${id}"]`).click();
  await page.locator(`[data-history-part="${id}|2026-10-14"]`).click();
  await manual(2).hover();assert.equal(await page.locator('.focus-cross-row').count(),1);assert.equal(await page.locator('.focus-cross-cell').count(),1);
  assert.ok(await page.locator('.line-final.focus-cross-column').count()>0);await shot('inline-history');
  await page.locator('[data-action="next"]').click();assert.equal(await page.locator('#rangeDisplay').textContent(),'2026/11/04 - 2026/11/17');
  const modelValue=await page.evaluate(()=>historicalSnapshots['2026-10-14']['US-B0GRG5DRWW']['2026-11-04'].final);
  assert.equal(await page.locator('[data-history-batch="2026-10-14"][data-history-kind="final"][data-time-column="date:2026-11-04"] > span').first().textContent(),String(modelValue));
  await page.locator('[data-action="previous"]').click();assert.match(await final().innerText(),/40\s*人工/);
  await page.locator('[data-week-toggle="2026-W43"]').click();assert.equal(await page.locator('.date-head').count(),10);
  const weekly=await page.evaluate(()=>aggregate(findChild('US-B0GRG5DRWW'),state.batch,visibleColumns()[0].days));
  assert.equal(await page.locator(`[data-week-detail="2026-W43"][data-asin="${id}"] > span`).first().textContent(),String(weekly));
  await page.locator('[data-week-toggle="2026-W43"]').click();console.log('Inline progressive history, target-date alignment across windows, future actual blank, cross highlighting and week totals PASS');
  await page.locator('[data-view="target"]').click();assert.equal(await page.locator('.target-table').count(),1);assert.equal(await page.locator('.drawer.show,.modal.show').count(),0);assert.equal(await page.locator('[data-target-batch="2026-10-21"] td').nth(4).textContent(),'40');
  await page.locator('[data-review-past]').click();assert.equal(await page.locator('#batchSelect').inputValue(),'2026-10-14');assert.match(await page.locator('#batchStatus').textContent(),/只读/);assert.equal(await page.locator('[data-edit-manual],[data-event]').count(),0);
  assert.match(await page.locator('.target-actual').textContent(),/实际销量 32/);assert.ok(!(await page.locator('.change-list').textContent()).includes('本批次调整记录'));await shot('target-date-review');
  await page.locator('#batchSelect').selectOption('2026-10-21');await page.locator('[data-view="batch"]').click();assert.match(await final().innerText(),/40\s*人工/);
  await page.locator('#columnConfigButton').click();assert.equal(await page.locator('[data-config-field]:disabled').count(),5);await shot('column-config');
  await page.locator('[data-config-field="combo"]').check();await page.locator('[data-config-close]').last().click();await page.locator('[data-config-discard]').click();assert.equal(await page.locator('.product-sub [data-code-tip^="销售组合"]').count(),0);
  await page.locator('#columnConfigButton').click();await page.locator('[data-config-field="combo"]').check();await page.locator('[data-config-move="adu7"][data-step="-1"]').click();await page.locator('#templateName').fill('对比工作台');await page.locator('[data-template-save]').click();await page.locator('[data-config-apply]').click();assert.equal(await page.locator('.product-sub [data-code-tip^="销售组合"]').count(),13);assert.equal(await page.locator('.context-cell .metric').first().getAttribute('data-field'),'adu7');
  await page.locator('#columnConfigButton').click();await page.locator('#configSearch').fill('在途');assert.equal(await page.locator('[data-config-field]').count(),1);await page.locator('#configSearch').fill('');
  await page.locator('#configTemplate').selectOption('compact');await page.locator('[data-config-field="stock"]').uncheck();await page.locator('[data-config-field="doi"]').uncheck();await page.locator('[data-config-apply]').click();assert.equal(await page.locator('.context-head').count(),0);assert.equal(await page.locator('.line-head').evaluate(e=>parseInt(getComputedStyle(e).left)),490);
  await page.locator('#columnConfigButton').click();await page.locator('#configTemplate').selectOption('0');await page.locator('[data-config-apply]').click();assert.equal(await page.locator('.context-head').count(),1);
  await page.reload();await page.locator(`[data-child-toggle="${id}"]`).first().click();assert.match(await final().innerText(),/40\s*人工/);assert.equal(await page.locator('.context-cell .metric').first().getAttribute('data-field'),'adu7');console.log('Historical readonly, same-scene target-date actual comparison, config protected fields/draft cancel/order/search/template/visibility/persistence PASS');
  await page.locator(`[data-note-edit="${id}"]`).click();await page.locator('[data-note-input]').fill('核对活动资源');await page.locator('[data-note-save]').click();await page.reload();assert.equal(await page.locator(`[data-note-edit="${id}"] .note-text`).textContent(),'核对活动资源');
  await page.locator('#market').selectOption('UK');await page.locator('[data-action="filter"]').click();assert.equal(await page.locator('[data-record-id]').count(),1);assert.equal(await page.locator('[data-record-id]').getAttribute('data-record-id'),uk);await page.locator('[data-action="reset"]').click();
  await page.locator('#pageSize').selectOption('5');assert.equal(await page.locator('[data-record-id]').count(),5);await page.locator('[data-page="2"]').first().click();assert.match(await page.locator('.page-total').textContent(),/13/);await page.locator('#pageSize').selectOption('20');
  await page.locator('#columnConfigButton').click();await page.locator('[data-config-reset]').click();await page.locator('[data-config-apply]').click();
  for(const [width,height] of [[1366,768],[1440,900],[1920,900]]){
   await page.setViewportSize({width,height});await page.locator('[data-tree="expand"]').click();
   const layout=await page.evaluate(()=>({body:document.documentElement.scrollWidth,view:innerWidth,footer:document.querySelector('.list-footer').getBoundingClientRect().bottom,scroll:document.querySelector('#horizontalScrollbar').getBoundingClientRect().bottom,footerTop:document.querySelector('.list-footer').getBoundingClientRect().top,wb:document.querySelector('#workbench').getBoundingClientRect().bottom,range:document.querySelector('.range-bar').getBoundingClientRect().height}));
   assert.ok(layout.body<=width);assert.ok(Math.abs(layout.footer-height)<1);assert.ok(Math.abs(layout.scroll-layout.footerTop)<1);assert.ok(layout.wb<=layout.scroll);assert.ok(layout.range<50);
   await shot('layout-'+width);
  }
  await page.setViewportSize({width:1440,height:900});
  const handle=await page.locator('[data-resize-column="identity"]').boundingBox();await page.mouse.move(handle.x+2,handle.y+15);await page.mouse.down();await page.mouse.move(handle.x+42,handle.y+15);await page.mouse.up();
  const before=await page.locator('col[data-column="identity"]').getAttribute('style');await page.locator('[data-range-size="30"]').click();assert.equal(await page.locator('col[data-column="identity"]').getAttribute('style'),before);assert.equal(await page.locator('.date-head').count(),30);
  await page.locator('#rangeDisplay').click();await page.locator('[data-calendar-preset="14"]').click();await page.locator('[data-calendar-apply]').click();assert.equal(await page.locator('.date-head').count(),14);
  await page.locator('#rangeDisplay').click();assert.equal(await page.locator('[data-calendar-preset="all"]').count(),0);await page.locator('[data-calendar-own="true"][aria-label="2026/10/21"]').click();await page.locator('[data-calendar-shift="1"]').click();await page.locator('[data-calendar-own="true"][aria-label="2026/12/01"]').click();await page.locator('[data-calendar-apply]').click();assert.match(await page.locator('.calendar-selection').textContent(),/最多31天/);await page.locator('[data-calendar-cancel]').click();
  await page.locator('[data-range-size="30"]').click();for(let i=0;i<6;i++)await page.locator('[data-action="next"]').click();assert.equal(await page.locator('.date-head').count(),2);assert.equal(await page.locator('[data-action="next"]').isDisabled(),true);await page.locator('[data-action="previous"]').click();assert.equal(await page.locator('.date-head').count(),30);
  assert.equal(await page.locator('.list-footer').evaluate(e=>e.getBoundingClientRect().bottom),900);assert.deepEqual(errors,[]);console.log('Notes, filters, pagination, 1366/1440/1920 fixed layout, column resize, date picker/31-day cap, non-overlapping terminal windows and zero page errors PASS');
 }catch(e){console.error(e);console.error('PAGE ERRORS:',errors);await shot('failure');process.exitCode=1;}finally{await browser.close();}
})();
