const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];
  page.setDefaultTimeout(10000);
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const shot=name=>page.screenshot({path:path.join(__dirname,'evidence','v033-'+name+'.png'),animations:'disabled'});
  const id='US-B0GRG5DRWW',text='推广资源和转化率低于原计划，因此调整本日销量；后续将依据站内资源安排及实际流量重新评估。';
  try{
    await page.goto('http://127.0.0.1:8800/?v=0.3.3',{waitUntil:'networkidle'});
    await page.locator('[data-tag-category]').first().waitFor();
    const labels=()=>page.locator('.week-heading > span').allTextContents();
    assert.ok((await labels()).every(x=>/^W\d+$/.test(x)));
    await shot('default');
    await page.locator('[data-week-toggle]').first().click();
    assert.ok((await labels()).every(x=>/^W\d+$/.test(x)));
    assert.match(await page.locator('th.week-collapsed.date-head').first().textContent(),/10\/21 ~ 10\/25/);
    await page.locator('[data-week-toggle]').first().click();
    const manual=page.locator(`[data-edit-manual="${id}"]`).first();
    assert.equal(await manual.locator('.entry-number').textContent(),'');
    await manual.click();
    const manualDialog=page.getByRole('dialog',{name:'人工预测',exact:true});
    await manualDialog.getByRole('spinbutton',{name:'预测销量'}).fill('0');
    await manualDialog.getByRole('button',{name:'保存',exact:true}).click();
    await manualDialog.getByText('请填写不采用AI预测的原因',{exact:true}).waitFor();
    await manualDialog.getByRole('textbox',{name:'人工预测原因'}).fill(text);
    await manualDialog.getByRole('button',{name:'保存',exact:true}).click();
    await manualDialog.waitFor({state:'hidden'});
    assert.equal((await page.locator(`[data-final="${id}"]`).first().textContent()).replace(/\s/g,''),'0(人工)');
    const reason=page.locator(`[data-reason-host="${id}"][data-reason-kind="manual"] .cell-reason`).first();
    await reason.hover();
    const pop=page.locator('.ant-popover:visible');
    await pop.waitFor();await page.waitForTimeout(250);
    assert.equal(await pop.getByRole('spinbutton',{name:'预测销量'}).inputValue(),'0');
    assert.equal(await pop.getByRole('textbox',{name:'人工预测原因'}).inputValue(),text);
    assert.equal(await pop.getByRole('textbox',{name:'人工预测原因'}).getAttribute('readonly'),'');
    assert.equal(await pop.getByRole('spinbutton',{name:'预测销量'}).getAttribute('readonly'),'');
    assert.deepEqual(await pop.locator('label').allTextContents(),['预测销量','人工预测原因']);
    const surface=await pop.locator('.ant-popover-inner').evaluate(el=>({bg:getComputedStyle(el).backgroundColor,border:getComputedStyle(el).borderTopWidth}));
    assert.equal(surface.bg,'rgb(255, 255, 255)');assert.equal(surface.border,'0px');
    assert.equal(await pop.locator('.ant-popover-arrow').count(),1);
    assert.equal(await pop.locator('.ant-popover-arrow').evaluate(el=>getComputedStyle(el,'::before').backgroundColor),'rgb(255, 255, 255)');
    const rb=await reason.boundingBox(),pb=await pop.boundingBox(),distance=rb.y-pb.y-pb.height;
    assert.ok(distance>=0&&distance<=16,JSON.stringify({rb,pb,distance}));
    console.log('reason anchor gap',distance);
    await shot('manual-preview');
    await page.keyboard.press('Escape');await pop.waitFor({state:'hidden'});await page.mouse.move(100,100);
    await page.locator(`[data-event="${id}"]`).first().click();
    const activity=page.getByRole('dialog',{name:'活动预测',exact:true});
    await activity.getByRole('spinbutton',{name:'预测销量'}).fill('1080');
    await activity.getByRole('textbox',{name:'活动名称'}).fill('秋季大促');
    await activity.getByRole('textbox',{name:'备注说明'}).fill(text.repeat(3));
    await activity.getByRole('button',{name:'保存',exact:true}).click();await activity.waitFor({state:'hidden'});
    assert.equal((await page.locator(`[data-final="${id}"]`).first().textContent()).replace(/\s/g,''),'1,080(活动)');
    const activityReason=page.locator(`[data-reason-host="${id}"][data-reason-kind="activity"] .cell-reason`).first();
    await activityReason.focus();await pop.waitFor();await page.waitForTimeout(250);
    assert.deepEqual(await pop.locator('label').allTextContents(),['预测销量','活动名称','活动日期','备注说明']);
    assert.equal(await pop.getByRole('spinbutton',{name:'预测销量'}).inputValue(),'1,080');
    assert.equal(await pop.getByRole('textbox',{name:'活动名称'}).inputValue(),'秋季大促');
    assert.equal(await pop.getByRole('textbox',{name:'活动日期'}).inputValue(),'2026/10/21');
    assert.equal(await pop.getByRole('textbox',{name:'备注说明'}).inputValue(),text.repeat(3));
    const ab=await pop.boundingBox();assert.ok(ab.y>=0&&ab.x>=0&&ab.x+ab.width<=1366&&ab.y+ab.height<=768);
    await shot('activity-preview');
    await pop.locator('.reason-preview').evaluate(el=>{el.scrollTop=el.scrollHeight;});
    assert.equal(await pop.isVisible(),true);
    await shot('activity-note');
    await page.keyboard.press('Escape');await pop.waitFor({state:'hidden'});
    await page.reload({waitUntil:'networkidle'});
    assert.equal((await page.locator(`[data-final="${id}"]`).first().textContent()).replace(/\s/g,''),'1,080(活动)');
    await page.goto('http://127.0.0.1:8800/index.v0.3.2.html',{waitUntil:'networkidle'});
    assert.equal(await page.locator('script[src*="v033"],link[href*="v033"]').count(),0);
    assert.deepEqual(errors,[]);
    console.log('PASS ISO week labels / week toggle / shared editor validation / zero and activity precedence / read-only field preview / white seamless arrow / reason-anchored position / viewport / scroll / Escape / persistence / archive');
  }catch(e){console.error(e);console.error(errors);await shot('failure');process.exitCode=1;}
  finally{await browser.close();}
})();
