const assert=require('node:assert/strict'),path=require('node:path'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext({viewport:{width:1440,height:900},permissions:['clipboard-read','clipboard-write']}),p=await ctx.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.setDefaultTimeout(10000);
 const shot=n=>p.screenshot({path:path.join(__dirname,'evidence','v028-'+n+'.png'),animations:'disabled'}),id='US-B0GRG5DRWW',goods=()=>p.locator('[data-record-id="'+id+'"]');
 try{
  await p.goto('http://127.0.0.1:8800/?v=0.2.8');await p.locator('.forecast-pagination input').waitFor();assert.deepEqual(errors,[]);
  const store=goods().locator('.child-store');assert.equal(await store.textContent(),'BRABIC-US');assert.equal(await store.evaluate(e=>getComputedStyle(e,'::before').content),'"丨"');assert.equal(await goods().locator('.product-meta [data-hint^="账号 / 店铺"]').count(),0);
  const asin=goods().locator('.child-asin-line .code-text'),sb=await store.boundingBox(),ab=await asin.boundingBox();assert.ok(sb.x>ab.x&&Math.abs(sb.y-ab.y)<5);
  const links=goods().locator('.sku-detail-link');assert.equal(await links.count(),2);for(const link of await links.all())assert.equal(await link.evaluate(e=>getComputedStyle(e).color),'rgb(72, 101, 242)');
  const button=p.locator('[data-history-count="'+id+'"]');assert.equal(await button.evaluate(e=>getComputedStyle(e).color),'rgb(31, 111, 235)');assert.equal(await button.locator('svg').evaluate(e=>getComputedStyle(e).color),'rgb(31, 111, 235)');
  const colors=await goods().locator('.product-action').evaluateAll(es=>es.map(e=>[getComputedStyle(e).color,getComputedStyle(e.querySelector('svg')).color]));assert.equal(new Set(colors.map(a=>a[1])).size,3);assert.ok(colors.every(([a,b])=>a!==b));
  await goods().locator('.thumb').hover();await p.locator('#imagePreview').waitFor({state:'visible'});assert.equal(await goods().locator('.thumb').evaluate(e=>getComputedStyle(e).cursor),'default');await shot('image-hover');await p.mouse.move(10,10);
  const widths=()=>p.locator('th.date-head').evaluateAll(es=>es.map(e=>Math.round(e.getBoundingClientRect().width)));assert.ok((await widths()).every(w=>w===104));
  await p.locator('.current-forecast-week [data-week-toggle]').click();assert.equal(await p.locator('th.week-collapsed.date-head').textContent(),'10/21-10/25');assert.equal(await p.locator('th.week-collapsed.date-head').evaluate(e=>e.getBoundingClientRect().width),128);await shot('week-collapsed');await p.locator('.current-forecast-week [data-week-toggle]').click();assert.ok((await widths()).every(w=>w===104));
  await p.locator('[data-range-size="30"]').click();assert.ok((await widths()).every(w=>w===104));await p.locator('[data-range-size="14"]').click();
  // Use real controls to retain selected rows and forecast data across page/route changes.
  const index=await p.evaluate(()=>indexForDate('2026-10-21'));await p.locator('[data-edit-manual="'+id+'"][data-index="'+index+'"]').click();await p.getByRole('spinbutton',{name:'预测销量'}).fill('1234');await p.getByRole('textbox',{name:'人工预测原因'}).fill('验证SKU跳转后保留填报');await p.getByRole('dialog',{name:'人工预测',exact:true}).getByRole('button',{name:'保存',exact:true}).click();await p.getByRole('dialog',{name:'人工预测',exact:true}).waitFor({state:'hidden'});
  await p.locator('#workbench').evaluate(e=>e.scrollLeft=120);const left=await p.locator('#workbench').evaluate(e=>e.scrollLeft);
  await links.first().click();await p.locator('.sku-workspace').waitFor({state:'visible'});assert.match(p.url(),/#sku=A1B2C3D/);assert.equal(await p.getByRole('tab',{name:'SKU详情列表',exact:true}).count(),1);assert.ok(await p.getByRole('cell',{name:'N0C0001A-91-XL',exact:true}).isVisible());assert.ok(await p.getByRole('cell',{name:'B0GRG5DRWW',exact:true}).count()>=1);await shot('sku-list');
  await p.getByRole('tab',{name:'销售预测提报',exact:true}).click();await goods().waitFor({state:'visible'});assert.equal(await p.locator('#workbench').evaluate(e=>e.scrollLeft),left);assert.match(await p.locator('[data-final="'+id+'"][data-index="'+index+'"]').textContent(),/1,234/);
  await links.last().click();await p.locator('.sku-workspace').waitFor({state:'visible'});assert.equal(await p.getByRole('tab',{name:'SKU详情列表',exact:true}).count(),1);await p.getByRole('link',{name:'返回销售预测提报',exact:true}).click();await goods().waitFor({state:'visible'});
  await links.first().locator('..').hover();await links.first().locator('..').getByRole('button').click();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'A1B2C3D');assert.match(p.url(),/#forecast/);
  const footer=p.locator('.forecast-pagination');assert.match(await footer.textContent(),/共 13 条，当前页 13 条/);await footer.getByTitle('20 条/页',{exact:true}).click();await p.getByTitle('5 条/页',{exact:true}).click();await p.waitForFunction(()=>state.pageSize===5);assert.equal(await p.locator('[data-record-id]').count(),5);await footer.getByTitle('2',{exact:true}).click();await p.waitForFunction(()=>state.page===2);assert.equal(await p.locator('[data-record-id]').count(),5);
  const jump=footer.getByRole('textbox');await jump.fill('3');await jump.press('Enter');await p.waitForFunction(()=>state.page===3);assert.equal(await p.locator('[data-record-id]').count(),3);await shot('pagination');await jump.fill('1');await jump.press('Enter');await p.waitForFunction(()=>state.page===1);assert.match(await p.locator('[data-final="'+id+'"][data-index="'+index+'"]').textContent(),/1,234/);
  for(const [width,height]of [[1366,768],[1440,900],[1920,900]]){await p.setViewportSize({width,height});await p.locator('#workbench').evaluate(e=>e.scrollTo(0,0));assert.equal(await p.locator('.list-footer').evaluate(e=>e.getBoundingClientRect().bottom),height);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('layout-'+width);}
  await p.goto('http://127.0.0.1:8800/index.v0.2.7.html');await p.locator('#antdColumnButton').waitFor();assert.equal(await p.locator('script[src*="v028"],link[href*="v028"]').count(),0);assert.deepEqual(errors,[]);console.log('V028 PASS seven changes / SKU routing and retained inputs / pagination size+page+jump / compact week columns / three layouts / archive');
 }catch(e){console.error(e);console.error(errors);await shot('failure');process.exitCode=1;}finally{await browser.close();}
})();
